CREATE TABLE attributes (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  data_type VARCHAR(20) NOT NULL,
  unit VARCHAR(30) NULL,
  is_filterable TINYINT(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB;
